### ISSUE TITLE
Can we convert it to a cmd tool

### ISSUE THREAD

**Issue by sivsivsree** [rahulvramesh/oreilly-books-grabber#1]
### 1. Login management 
For example like,   **git login** or **heroku login** and save the details in a secure file or some hashed environment variables.

**Comment by rahulvramesh** [comment]
on it, just trying out the basic flow.  once i finish the epub part, i  will be refactoring the code.

thanks for the login idea, will add that in to the list.

@sivsivsree  feel free to contribute :)
